// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TDT4900_MasterThesis.Context;

#nullable disable

namespace TDT4900_MasterThesis.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20250312125646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.AlgorithmSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlgorithmType")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("AlgorithmSpecs");

                    b.HasDiscriminator().HasValue("AlgorithmSpec");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GraphId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Edge");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Graph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Graphs");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.GraphSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GraphSpecs");

                    b.HasDiscriminator().HasValue("GraphSpec");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GraphId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.HasIndex("SimulationId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.NodeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("NodeEvents");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Simulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgorithmSpecId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GraphId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GraphSpecId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StartNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmSpecId");

                    b.HasIndex("GraphId");

                    b.HasIndex("GraphSpecId");

                    b.HasIndex("SimulationBatchId");

                    b.HasIndex("StartNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.SimulationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SimulationBatches");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.AlphaAlgorithmSpec", b =>
                {
                    b.HasBaseType("TDT4900_MasterThesis.Model.Db.AlgorithmSpec");

                    b.Property<int>("DeltaTExcitatory")
                        .HasColumnType("integer");

                    b.Property<int>("DeltaTInhibitory")
                        .HasColumnType("integer");

                    b.Property<int>("RefractoryPeriod")
                        .HasColumnType("integer");

                    b.Property<int>("TauPlus")
                        .HasColumnType("integer");

                    b.Property<int>("TauZero")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("AlphaAlgorithmSpec");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.NeighboringGraphSpec", b =>
                {
                    b.HasBaseType("TDT4900_MasterThesis.Model.Db.GraphSpec");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<int>("Noise")
                        .HasColumnType("integer");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("NeighboringGraphSpec");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Edge", b =>
                {
                    b.HasOne("TDT4900_MasterThesis.Model.Db.Graph", null)
                        .WithMany("Edges")
                        .HasForeignKey("GraphId");

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Node", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Node", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Node", b =>
                {
                    b.HasOne("TDT4900_MasterThesis.Model.Db.Graph", null)
                        .WithMany("Nodes")
                        .HasForeignKey("GraphId");

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Simulation", null)
                        .WithMany("TaggedNodes")
                        .HasForeignKey("SimulationId");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.NodeEvent", b =>
                {
                    b.HasOne("TDT4900_MasterThesis.Model.Db.Simulation", null)
                        .WithMany("NodeEvents")
                        .HasForeignKey("SimulationId");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Simulation", b =>
                {
                    b.HasOne("TDT4900_MasterThesis.Model.Db.AlgorithmSpec", "AlgorithmSpec")
                        .WithMany()
                        .HasForeignKey("AlgorithmSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Graph", "Graph")
                        .WithMany()
                        .HasForeignKey("GraphId");

                    b.HasOne("TDT4900_MasterThesis.Model.Db.GraphSpec", "GraphSpec")
                        .WithMany()
                        .HasForeignKey("GraphSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDT4900_MasterThesis.Model.Db.SimulationBatch", null)
                        .WithMany("Simulations")
                        .HasForeignKey("SimulationBatchId");

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Node", "StartNode")
                        .WithMany()
                        .HasForeignKey("StartNodeId");

                    b.HasOne("TDT4900_MasterThesis.Model.Db.Node", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId");

                    b.Navigation("AlgorithmSpec");

                    b.Navigation("Graph");

                    b.Navigation("GraphSpec");

                    b.Navigation("StartNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Graph", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.Simulation", b =>
                {
                    b.Navigation("NodeEvents");

                    b.Navigation("TaggedNodes");
                });

            modelBuilder.Entity("TDT4900_MasterThesis.Model.Db.SimulationBatch", b =>
                {
                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
